name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - name: Build
      run: bash build.sh

    - name: Test
      working-directory: ${{runner.workspace}}/n-fold-solver/build
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{runner.workspace}}/n-fold-solver/build/test-results/**/*.xml
